name: CI - Integration Test

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Git checkout
        uses: actions/checkout@v2

      - name: Install Node JS
        uses: actions/setup-node@v1
        with:
          node-version: v20.16.0

      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Run Integrations
        env:
          API_URL: ${{ secrets.API_URL }}
        run: mvn clean integration-test